packages:
  - "apps/*"
  - "packages/*"

# pnpm v10+ 可能默认忽略依赖的安装脚本（native/二进制包会因此不可用）。
# Desktop 需要 Electron（下载运行时）与 better-sqlite3（编译/预构建）执行安装脚本。
onlyBuiltDependencies:
  - electron
  - better-sqlite3

# 保持原有 Web 的策略：这些依赖的构建脚本不运行（避免安装失败或不必要的构建）。
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
